# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "조은채의 블로그"
description: "It is created for the team project of the 2020-1 semester open source software class." 
email: "dmsco9835@naver.com"

#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/light-bulb.jpg"

name: 'JoEunchae'
author: 'JoEunchae'
author_image: "/assets/images/profile.png"

paginate:	5

url: "https://joeunchae9835_1.github.io"
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/Joeunchae9835
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:
